#!/bin/sh -e
error() {
	echo "ERROR: $@" >&2
	exit 1
}

usage () {
    echo "Usage:"
    echo "    $0 <path-to-local-repo> [commit (defaults to HEAD)]"
    exit 1
}

if [ -z "$1" ]; then
    usage
    if [ ! -f $1 ]; then
        error "Local branch location does not exist. Cannot proceed"
    fi
fi

if [ -z "$2" ]; then
    echo "WARNING: No commit specified, using HEAD instead"
    COMMIT="HEAD"
else
    COMMIT="$2"
fi

PKG=$(head -n1 debian/changelog | awk '{print $1}')
MAJOR_VER=$(head -n 1 debian/changelog | sed 's/^.*(//' | sed 's/).*//' | sed 's/-.*//')
#REV=$(head -n 1 debian/changelog | sed -rne 's,.*[+~.]git([0-9a-zA-Z]+).*,\1,p')
REV_COUNT=$(git -C $1 rev-list --count $COMMIT)
REV_SHORT=$(git -C $1 rev-parse --short $COMMIT)
FULL_VER="$MAJOR_VER-$REV_COUNT-g$REV_SHORT"
TARBALL="maas_$FULL_VER.orig.tar.gz"

get_orig_source() {
        branch="$1"
        git -C $branch archive --format=tar.gz --prefix="maas-$FULL_VER.orig/" $COMMIT -o $TARBALL
	
}
# Obtain the tarball from a local branch
get_orig_source $1 $FULL_VER $REV

# Copy the tarball to the local dir
mv "${1}/${TARBALL}" .

# Update the changelog
sed -i "s/${MAJOR_VER}-0ubuntu1/${FULL_VER}-0ubuntu1/i" debian/changelog

# Untar
tar zxvf ${PKG}_${FULL_VER}.orig.tar.gz
cd "${PKG}-${FULL_VER}.orig/"
cp -r ../debian .
sed -i "s/) UNRELEASED;/~16.04.1) xenial;/i" debian/changelog
debuild -S -sa
sed -i "s/~16.04.1) xenial;/~16.10.1) yakkety;/" debian/changelog
debuild -S
sed -i "s/~16.10.1) yakkety;/~17.04.1) zesty;/" debian/changelog
debuild -S
sed -i "s/~17.04.1) zesty;/~17.10.1) artful;/" debian/changelog
debuild -S

cd ../
sed -i "s/${FULL_VER}-0ubuntu1/${MAJOR_VER}-0ubuntu1/i" debian/changelog
