#!/bin/sh
if [ "`expr \"$0\" : \".*maas-cli*\"`" != "0" ];then
    echo "  WARNING: The maas-cli command is deprecated and will be removed" \
         "in a future\n  version.  From now on please use 'maas' instead."
fi
exec python -m maascli "$@"
