#!/usr/bin/python3
# Copyright 2015 Canonical Ltd.  This software is licensed under the
# GNU Affero General Public License version 3 (see the file LICENSE).

import sys

sys.stderr.write("""
  WARNING: The maas-provision command is deprecated and will be removed in a future
  version. From now on please use 'maas-rack' instead.
""")
