#!/bin/sh
if [ "$(id -u)" != "0" ]; then
    echo "This utility may only be run as root." 1>&2
    exit 1
fi
export PYTHONPATH="/usr/share/maas${PYTHONPATH:+:}${PYTHONPATH}"
exec /usr/bin/python -m provisioningserver.dhcp.probe "$@"
