#!/usr/bin/python
import os
import sys

user_id = os.getuid()
if user_id != 0:
    print("This utility may only be run as root.")
    sys.exit(1)

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "maas.settings")
sys.path.append('/usr/share/maas')

from django.core import management

if __name__ == "__main__":
    management.execute_from_command_line()
