#!/bin/sh

set -e

#DEBHELPER#

case "$1" in
        purge)
                # remove log directory
		rm -rf /var/log/maas
		# remove var directory
		rm -rf /var/lib/maas/celerybeat-cluster-schedule
		DIR=/var/lib/maas
		if [ "$(ls -A $DIR 2> /dev/null)" = "" ]; then
			rm -rf /var/lib/maas
		fi

		# Delete symlink for iSCSI config.
		if [ -L /etc/tgt/conf.d/maas.conf ]; then
			rm -rf /etc/tgt/conf.d/maas.conf
		fi

esac
