# Install templates
debian/tmp/etc/maas/templates/dhcp
debian/tmp/etc/maas/templates/power
debian/tmp/etc/maas/templates/pxe
debian/tmp/etc/maas/templates/uefi

# Install uec2roottar
debian/tmp/usr/bin/uec2roottar

# Install maas-dhcp-helper
debian/tmp/usr/sbin/maas-dhcp-helper

# Install all other stuff
debian/extras/99-maas-sudoers etc/sudoers.d
debian/extras/maas-probe-dhcp usr/sbin
debian/extras/maas-rack usr/sbin
