#!/bin/sh

set -e

. /usr/share/debconf/confmodule

if [ "$1" = "upgrade" ] && dpkg --compare-versions "$2" lt 1.7.0~beta3+bzr3066-0ubuntu1; then

    if [ -f /etc/init/maas-pserv.conf ]; then
        invoke-rc.d maas-pserv stop
    fi

    if [ -f /etc/init/maas-cluster-celery.conf ]; then
        invoke-rc.d maas-cluster-celery stop
    fi

    if [ -f /var/log/maas/celery.log ]; then
        rm -rf /var/log/maas/celery.log
    fi

fi

#DEBHELPER#
