# Install project
debian/tmp/usr/lib/python*/dist-packages/maas usr/share/maas
twisted/plugins/maasps.py usr/share/pyshared/twisted/plugins

# Install static files
debian/tmp/usr/share/maas/web/static

# Install Apache Config
debian/tmp/etc/maas/maas-http.conf

# Install MAAS local settings
debian/tmp/etc/maas/maas_local_settings.py

# Install MAAS local celery settings
debian/tmp/etc/maas/maas_local_celeryconfig.py

# Install WSGI
debian/tmp/usr/share/maas/wsgi.py

# Install PSERV, txlongpoll config files
debian/tmp/etc/maas/pserv.yaml
debian/tmp/etc/maas/txlongpoll.yaml

# Install Celery Config
debian/tmp/etc/maas/celeryconfig.py

# Install maas-import-pxe-files
debian/tmp/usr/sbin/maas-import-pxe-files

# Install maas-import-pxe-files and related files
etc/cron.d/maas-import-pxe-files
etc/maas/import_pxe_files
man/maas-import-pxe-files.8 usr/share/man/man8
debian/tmp/usr/sbin/maas-import-ephemerals
debian/tmp/etc/maas/import_ephemerals
debian/tmp/etc/maas/commissioning-user-data
# Obsolete, but still available for compatibility:
scripts/maas-import-isos usr/sbin

# Install new preseed files
debian/tmp/usr/share/maas/preseeds

# Install cronjobs
debian/tmp/etc/cron.d/maas-gc

# Install all other stuff
debian/extras/maas usr/sbin
debian/extras/maas-provision usr/sbin
debian/extras/20-maas.conf etc/rsyslog.d
debian/extras/maas_remote_syslog_compress etc/cron.d
debian/extras/99-maas etc/squid-deb-proxy/mirror-dstdomain.acl.d
debian/extras/99-maas-sudoers etc/sudoers.d
