# Install twisted plugins
twisted/plugins/maasclusterd.py usr/share/pyshared/twisted/plugins

# Install PSERV config file
debian/tmp/etc/maas/pserv.yaml

# Install cluster config file
debian/tmp/etc/maas/maas_cluster.conf

# Install templates
debian/tmp/etc/maas/templates/dhcp
debian/tmp/etc/maas/templates/power
debian/tmp/etc/maas/templates/pxe
debian/tmp/etc/maas/templates/uefi

# Install uec2roottar
debian/tmp/usr/bin/uec2roottar

# Install all other stuff
debian/extras/99-maas-sudoers etc/sudoers.d
debian/extras/isc-dhcp-server.override etc/init
