# Install project
debian/tmp/usr/lib/python*/dist-packages/maas usr/share/maas

# Install static files
debian/tmp/usr/share/maas/web/static

# Install Apache Config
debian/tmp/etc/maas/maas-http.conf

# Install MAAS local settings
debian/tmp/etc/maas/maas_local_settings.py

# Install new preseed files
debian/tmp/etc/maas/preseeds

# Install templates
debian/tmp/etc/maas/templates/dns
debian/tmp/etc/maas/templates/commissioning-user-data
debian/tmp/etc/maas/templates/deployment-user-data

# Install driver configuration file
debian/tmp/etc/maas/drivers.yaml

# Install winrm certificate generation script
debian/tmp/usr/bin/maas-generate-winrm-cert

# Install twisted plugins
twisted/plugins/maasregiond.py usr/share/pyshared/twisted/plugins

# Install all other stuff
debian/extras/maas-region-admin usr/sbin
debian/extras/20-maas.conf etc/rsyslog.d
debian/extras/maas_remote_syslog_compress etc/cron.d
debian/extras/99-maas usr/share/maas/conf
