# Install twisted plugins
twisted/plugins/maasps.py usr/share/pyshared/twisted/plugins

# Install PSERV config files
debian/tmp/etc/maas/pserv.yaml
debian/tmp/etc/maas/bootresources.yaml

# Install cluster config file
debian/tmp/etc/maas/maas_cluster.conf

# Install celery config file
debian/tmp/usr/share/maas/celeryconfig_cluster.py

# Install local celery cluster config file
debian/tmp/etc/maas/maas_local_celeryconfig_cluster.py

# Install templates
debian/tmp/etc/maas/templates/dhcp
debian/tmp/etc/maas/templates/power
debian/tmp/etc/maas/templates/pxe

# Install maas-import-pxe-files and related files
debian/tmp/usr/sbin/maas-import-pxe-files
man/maas-import-pxe-files.8 usr/share/man/man8
debian/tmp/etc/maas/import_ephemerals
debian/tmp/etc/maas/import_pxe_files
debian/tmp/usr/sbin/maas-import-ephemerals
debian/tmp/usr/bin/uec2roottar

# Install all other stuff
debian/extras/99-maas-sudoers etc/sudoers.d
debian/extras/isc-dhcp-server.override etc/init
debian/tmp/etc/maas/maas-cluster-http.conf
