#!/bin/sh -e

if [ "$1" = "remove" ]; then
	if [ -f /etc/bind/named.conf.local ]; then
		sed -i '/^include.*\"\/etc\/bind\/maas\/named.conf.maas\"\;$/d' \
			/etc/bind/named.conf.local
	fi
fi

if [ "$1" = "purge" ]; then
	# Remove zone files
	if [ -d /etc/bind/maas ]; then
		rm -rf /etc/bind/maas
        fi
fi

if [ -x /usr/sbin/invoke-rc.d ]; then
	invoke-rc.d bind9 restart || true
fi

#DEBHELPER#

exit 0

