# Install project
debian/tmp/usr/lib/python*/dist-packages/maas usr/share/maas

# Install static files
debian/tmp/usr/share/maas/web/static

# Install Apache Config
debian/tmp/etc/maas/maas-http.conf

# Install MAAS local settings
debian/tmp/etc/maas/maas_local_settings.py

# Install celery config file
debian/tmp/usr/share/maas/celeryconfig.py

# Install local celery region config file
debian/tmp/etc/maas/maas_local_celeryconfig.py

# Install WSGI
debian/tmp/usr/share/maas/wsgi.py

# Install txlongpoll config file
debian/tmp/etc/maas/txlongpoll.yaml

# Install maas-import-pxe-files
debian/tmp/usr/sbin/maas-import-pxe-files

# Install maas-import-pxe-files and related files
etc/cron.d/maas-import-pxe-files
man/maas-import-pxe-files.8 usr/share/man/man8
debian/tmp/etc/maas/import_pxe_files
debian/tmp/usr/sbin/maas-import-squashfs
debian/tmp/etc/maas/import_squashfs
debian/tmp/usr/sbin/maas-import-ephemerals
debian/tmp/etc/maas/import_ephemerals
debian/tmp/etc/maas/commissioning-user-data
# Obsolete, but still available for compatibility:
scripts/maas-import-isos usr/sbin

# Install new preseed files
debian/tmp/usr/share/maas/preseeds

# Install all other stuff
debian/extras/maas usr/sbin
debian/extras/maas-region-celeryd usr/sbin
debian/extras/20-maas.conf etc/rsyslog.d
debian/extras/maas_remote_syslog_compress etc/cron.d
debian/extras/99-maas usr/share/maas/conf
