# Install twisted plugins
twisted/plugins/maasps.py usr/share/pyshared/twisted/plugins

# Install PSERV config file
debian/tmp/etc/maas/pserv.yaml

# Install cluster config file
debian/tmp/etc/maas/maas_cluster.conf

# Install celery config file
debian/tmp/usr/share/maas/celeryconfig_cluster.py

# Install local celery cluster config file
debian/tmp/etc/maas/maas_local_celeryconfig_cluster.py

# Install all other stuff
debian/extras/99-maas-sudoers etc/sudoers.d
debian/extras/isc-dhcp-server.override etc/init
